# Generated by Django 5.2.11 on 2026-02-18 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_data', '0004_remove_event_event_mode_delete_eventmode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by', to='core_data.poicategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_category_preferences',
                'indexes': [models.Index(fields=['user'], name='user_catego_user_id_7a96a6_idx'), models.Index(fields=['category'], name='user_catego_categor_04a7b6_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
