# Generated by Django 5.2.11 on 2026-02-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='prefers_indoor',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prefers_outdoor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('family', 'Family'), ('friends', 'Friends'), ('couple', 'Couple')], default='solo', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='outdoor_preference',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='walk_tolerance',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='budget_level',
            field=models.IntegerField(default=3),
        ),
    ]
