# Generated by Django 5.2.11 on 2026-02-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0003_remove_userprofile_prefers_indoor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('family', 'Family'), ('friends', 'Friends')], default='solo', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='outdoor_preference',
            field=models.FloatField(default=0.5),
        ),
    ]
