# Generated by Django 5.2.11 on 2026-02-15 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_geo', models.CharField(max_length=50, unique=True)),
                ('city_name_ar', models.CharField(max_length=100)),
                ('region_name_ar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='POICategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level1', models.CharField(max_length=100)),
                ('level2', models.CharField(blank=True, max_length=100, null=True)),
                ('level3', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'poi_categories',
                'indexes': [models.Index(fields=['level1'], name='poi_categor_level1_13a9a3_idx'), models.Index(fields=['source'], name='poi_categor_source_13d183_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=150)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core_data.city')),
            ],
            options={
                'db_table': 'districts',
                'indexes': [models.Index(fields=['city'], name='districts_city_id_7e72ef_idx'), models.Index(fields=['district_name'], name='districts_distric_fb3bee_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_male_allowed', models.BooleanField(blank=True, null=True)),
                ('is_female_allowed', models.BooleanField(blank=True, null=True)),
                ('is_family_allowed', models.BooleanField(blank=True, null=True)),
                ('event_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core_data.city')),
            ],
            options={
                'db_table': 'events',
                'indexes': [models.Index(fields=['city'], name='events_city_id_c50c2f_idx'), models.Index(fields=['start_date'], name='events_start_d_6c01fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('poi_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('traffic_score', models.FloatField(blank=True, null=True)),
                ('time_spent', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pois', to='core_data.city')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pois', to='core_data.poicategory')),
            ],
            options={
                'db_table': 'pois',
                'indexes': [models.Index(fields=['city'], name='pois_city_id_133a2f_idx'), models.Index(fields=['category'], name='pois_categor_8ee6fa_idx'), models.Index(fields=['rating'], name='pois_rating_acbc29_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherContext',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('temperature_avg', models.FloatField(blank=True, null=True)),
                ('temperature_min', models.FloatField(blank=True, null=True)),
                ('temperature_max', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('solar_index', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='solar', max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='core_data.city')),
            ],
            options={
                'db_table': 'weather_context',
                'indexes': [models.Index(fields=['city', 'date'], name='weather_con_city_id_711d64_idx')],
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('forecast_id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_time', models.DateTimeField()),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('weather_main', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='openweather', max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core_data.city')),
            ],
            options={
                'db_table': 'weather_forecasts',
                'indexes': [models.Index(fields=['city', 'forecast_time'], name='weather_for_city_id_6417fa_idx')],
                'unique_together': {('city', 'forecast_time')},
            },
        ),
    ]
