# Generated by Django 5.2.11 on 2026-02-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='district',
            name='districts_distric_fb3bee_idx',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='district_name',
            new_name='district_name_ar',
        ),
        migrations.AddField(
            model_name='district',
            name='district_name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['district_name_ar'], name='districts_distric_ec1b18_idx'),
        ),
    ]
