# Generated by Django 5.2.11 on 2026-02-16 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0002_remove_district_districts_distric_fb3bee_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMode',
            fields=[
                ('mode_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'event_modes',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='event_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core_data.eventmode'),
        ),
    ]
