# Generated by Django 5.2.11 on 2026-02-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0003_eventmode_alter_event_event_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_mode',
        ),
        migrations.DeleteModel(
            name='EventMode',
        ),
    ]
