# Generated by Django 5.2.11 on 2026-02-19 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0004_remove_event_event_mode_delete_eventmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core_data.poicategory'),
        ),
    ]
